### PR TITLE
Improvement to support deploy in WildFly/JBoss domain mode

### PR DESCRIPTION
**Pull request by amadeubarbosa**
Review of CLI commands and its parameters in order to support the specification of one server-group. Now there is a new 'domainServerGroup' property in FileDeployer.kt that allows specify the server-group. If empty, it'll proceed to standalone deployment as before.

### CODE REVIEW

**Comment by Ingwersaft** [comment]
Hey, thanks for your contribution!
I'll take a deeper look later this week when I have more time, but a first skim looks promising.

**Comment by amadeubarbosa** [comment]
Should I do a rebase to your most recent master or should I create a PR to another branch? I've tested these modifications on WildFly 15 runtime but AFAIK works the same in JBoss EAP.

**Comment by Ingwersaft** [comment]
Sorry, was trying to  get some CI up before taking a closer look into your PR and somehow closed/broke it on the way... force pushing is always a bad idea, sorry again :)

If you want I can just add your changes to master, or you can open the PR again, up to you.

**Comment by amadeubarbosa** [comment]
> Sorry, was trying to get some CI up before taking a closer look into your PR and somehow closed/broke it on the way... force pushing is always a bad idea, sorry again :)
> 
> If you want I can just add your changes to master, or you can open the PR again, up to you.

No problem, I'll create a new PR. I just rebase my fork up to your master. 
I pretend keep my fork updated for further contributions ;)

Thank you!

**Pull request closed without merging**
